name = "Actually Additions"
filename = "ActuallyAdditions-1.12.2-r151-2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2844/115/ActuallyAdditions-1.12.2-r151-2.jar"
hash-format = "murmur2"
hash = "1671041874"

[update]
[update.curseforge]
file-id = 2844115
project-id = 228404
release-channel = "beta"
