name = "AgriCraft"
filename = "AgriCraft-2.12.0-1.12.0-a6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2609/648/AgriCraft-2.12.0-1.12.0-a6.jar"
hash-format = "murmur2"
hash = "718550955"

[update]
[update.curseforge]
file-id = 2609648
project-id = 225635
release-channel = "beta"
