name = "Binnie's Mods"
filename = "binnie-mods-1.12.2-2.5.1.203.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2916/129/binnie-mods-1.12.2-2.5.1.203.jar"
hash-format = "murmur2"
hash = "3058542917"

[update]
[update.curseforge]
file-id = 2916129
project-id = 223525
release-channel = "beta"
