name = "Botania"
filename = "Botania r1.10-363.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2846/950/Botania r1.10-363.jar"
hash-format = "murmur2"
hash = "3763127432"

[update]
[update.curseforge]
file-id = 2846950
project-id = 225643
release-channel = "beta"
