name = "Chameleon"
filename = "Chameleon-1.12-4.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2450/900/Chameleon-1.12-4.1.3.jar"
hash-format = "murmur2"
hash = "2760206313"

[update]
[update.curseforge]
file-id = 2450900
project-id = 230497
release-channel = "beta"
