name = "Charset Lib"
filename = "Charset-Lib-0.5.6.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2816/636/Charset-Lib-0.5.6.4.jar"
hash-format = "murmur2"
hash = "1083033065"

[update]
[update.curseforge]
file-id = 2816636
project-id = 284523
release-channel = "beta"
