name = "Common Capabilities"
filename = "CommonCapabilities-1.12.2-2.4.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2920/804/CommonCapabilities-1.12.2-2.4.6.jar"
hash-format = "murmur2"
hash = "410869736"

[update]
[update.curseforge]
file-id = 2920804
project-id = 247007
release-channel = "beta"
