name = "Ender Storage 1.8.+"
filename = "EnderStorage-1.12.2-2.4.6.137-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2755/787/EnderStorage-1.12.2-2.4.6.137-universal.jar"
hash-format = "murmur2"
hash = "3887579715"

[update]
[update.curseforge]
file-id = 2755787
project-id = 245174
release-channel = "beta"
