name = "FastWorkbench"
filename = "FastWorkbench-1.12.2-1.7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2838/777/FastWorkbench-1.12.2-1.7.3.jar"
hash-format = "murmur2"
hash = "2436194208"

[update]
[update.curseforge]
file-id = 2838777
project-id = 288885
release-channel = "beta"
