name = "FoamFix​"
filename = "foamfix-0.10.10-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2845/668/foamfix-0.10.10-1.12.2.jar"
hash-format = "murmur2"
hash = "3326311587"

[update]
[update.curseforge]
file-id = 2845668
project-id = 278494
release-channel = "beta"
