name = "FTB Backups"
filename = "FTBBackups-1.1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2819/669/FTBBackups-1.1.0.1.jar"
hash-format = "murmur2"
hash = "752442057"

[update]
[update.curseforge]
file-id = 2819669
project-id = 314904
release-channel = "beta"
