name = "LibVulpes"
filename = "LibVulpes-1.12.2-0.4.2-74-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2878/931/LibVulpes-1.12.2-0.4.2-74-universal.jar"
hash-format = "murmur2"
hash = "2303900596"

[update]
[update.curseforge]
file-id = 2878931
project-id = 236541
release-channel = "beta"
