name = "MCMultiPart"
filename = "MCMultiPart-2.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2615/930/MCMultiPart-2.5.3.jar"
hash-format = "murmur2"
hash = "909753984"

[update]
[update.curseforge]
file-id = 2615930
project-id = 239431
release-channel = "beta"
