name = "Morpheus"
filename = "Morpheus-1.12.2-3.5.106.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2664/449/Morpheus-1.12.2-3.5.106.jar"
hash-format = "murmur2"
hash = "783395017"

[update]
[update.curseforge]
file-id = 2664449
project-id = 69118
release-channel = "beta"
