name = "Neat"
filename = "Neat 1.4-17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2595/310/Neat 1.4-17.jar"
hash-format = "murmur2"
hash = "851629213"

[update]
[update.curseforge]
file-id = 2595310
project-id = 238372
release-channel = "beta"
