name = "OpenComputers"
filename = "OpenComputers-MC1.12.2-1.7.5.192.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2828/357/OpenComputers-MC1.12.2-1.7.5.192.jar"
hash-format = "murmur2"
hash = "3597605255"

[update]
[update.curseforge]
file-id = 2828357
project-id = 223008
release-channel = "beta"
