name = "Ore Excavation"
filename = "OreExcavation-1.4.150.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2897/369/OreExcavation-1.4.150.jar"
hash-format = "murmur2"
hash = "424401967"

[update]
[update.curseforge]
file-id = 2897369
project-id = 250898
release-channel = "beta"
