name = "Placebo"
filename = "Placebo-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2510/621/Placebo-1.0.0.jar"
hash-format = "murmur2"
hash = "4278676777"

[update]
[update.curseforge]
file-id = 2510621
project-id = 283644
release-channel = "beta"
