name = "Shadowfacts' Forgelin"
filename = "Forgelin-1.8.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2785/465/Forgelin-1.8.4.jar"
hash-format = "murmur2"
hash = "387064965"

[update]
[update.curseforge]
file-id = 2785465
project-id = 248453
release-channel = "beta"
