name = "SimpleLogic Wires"
filename = "SimpleLogic-Wires-0.5.6.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2754/601/SimpleLogic-Wires-0.5.6.3.jar"
hash-format = "murmur2"
hash = "2485802666"

[update]
[update.curseforge]
file-id = 2754601
project-id = 298029
release-channel = "beta"
