name = "Storage Drawers"
filename = "StorageDrawers-1.12.2-5.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2887/858/StorageDrawers-1.12.2-5.4.1.jar"
hash-format = "murmur2"
hash = "2630207210"

[update]
[update.curseforge]
file-id = 2887858
project-id = 223852
release-channel = "beta"
