name = "The One Probe"
filename = "theoneprobe-1.12-1.4.28.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2667/280/theoneprobe-1.12-1.4.28.jar"
hash-format = "murmur2"
hash = "2094495496"

[update]
[update.curseforge]
file-id = 2667280
project-id = 245211
release-channel = "beta"
