name = "Thermal Expansion"
filename = "ThermalExpansion-1.12.2-5.5.6.1-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2920/438/ThermalExpansion-1.12.2-5.5.6.1-universal.jar"
hash-format = "murmur2"
hash = "2428122260"

[update]
[update.curseforge]
file-id = 2920438
project-id = 69163
release-channel = "beta"
