name = "Tinkers' Complement"
filename = "TinkersComplement-1.12.2-0.4.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2843/439/TinkersComplement-1.12.2-0.4.3.jar"
hash-format = "murmur2"
hash = "606935708"

[update]
[update.curseforge]
file-id = 2843439
project-id = 272671
release-channel = "beta"
