name = "Tinkers Construct"
filename = "TConstruct-1.12.2-2.13.0.183.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2902/483/TConstruct-1.12.2-2.13.0.183.jar"
hash-format = "murmur2"
hash = "3094578446"

[update]
[update.curseforge]
file-id = 2902483
project-id = 74072
release-channel = "beta"
