name = "UniDict"
filename = "UniDict-1.12.2-2.9.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2880/863/UniDict-1.12.2-2.9.6.jar"
hash-format = "murmur2"
hash = "2633447900"

[update]
[update.curseforge]
file-id = 2880863
project-id = 244258
release-channel = "beta"
