name = "WanionLib"
filename = "WanionLib-1.12.2-2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2807/433/WanionLib-1.12.2-2.4.jar"
hash-format = "murmur2"
hash = "1149245224"

[update]
[update.curseforge]
file-id = 2807433
project-id = 253043
release-channel = "beta"
