name = "Wireless Crafting Terminal"
filename = "WirelessCraftingTerminal-1.12.2-3.12.97.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2830/252/WirelessCraftingTerminal-1.12.2-3.12.97.jar"
hash-format = "murmur2"
hash = "2705844675"

[update]
[update.curseforge]
file-id = 2830252
project-id = 244559
release-channel = "beta"
